services:
  backend:
    build:
      context: ./todo-jenkins/backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./todo-jenkins/frontend
    ports:
      - "3000:80"

  jenkins:
    build:
      context: ./todo-jenkins/jenkins
    ports:
      - "8080:8080"
