// pipeline {
//     agent any

//     stages {

//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }

//         stage('Backend Test') {
//             steps {
//                 sh '''
//                     docker run --rm \
//                       -v "$PWD/todo-jenkins/backend:/app" \
//                       -w /app \
//                       node:22-alpine \
//                       sh -c "npm ci && npm test"
//                 '''
//             }
//         }

//         stage('Frontend Build') {
//             steps {
//                 sh '''
//                     docker run --rm \
//                       -v "$PWD/todo-jenkins/frontend:/app" \
//                       -w /app \
//                       node:22-alpine \
//                       sh -c "npm ci && npm run build"
//                 '''
//             }
//         }

//         stage('Docker Build') {
//             steps {
//                 sh '''
//                     docker compose build
//                 '''
//             }
//         }
//     }
// }

// pipeline {
//     agent any

//     stages {
//         stage('Backend Test') {
//             steps {
//                 dir('todo-jenkins/backend') {
//                     sh '''
//                         docker run --rm \
//                           -v "$PWD:/app" \
//                           -w /app \
//                           node:22-alpine \
//                           sh -c "npm ci && npm test"
//                     '''
//                 }
//             }
//         }

//         stage('Frontend Build') {
//             steps {
//                 dir('todo-jenkins/frontend') {
//                     sh '''
//                         docker run --rm \
//                           -v "$PWD:/app" \
//                           -w /app \
//                           node:22-alpine \
//                           sh -c "npm ci && npm run build"
//                     '''
//                 }
//             }
//         }

//         stage('Docker Build') {
//             steps {
//                 dir('todo-jenkins') {
//                     sh '''
//                         docker compose build
//                     '''
//                 }
//             }
//         }
//     }

//     post {
//         always {
//             // Clean up files generated by root inside containers to avoid workspace permission issues
//             cleanWs deleteDirs: true, notFailBuild: true
//         }
//     }
// }

pipeline {
    agent any

    stages {
        stage('Backend Test') {
            steps {
                dir('todo-jenkins/backend') {
                    sh '''
                        podman run --rm \
                          -v "$PWD:/app" \
                          -w /app \
                          node:22-alpine \
                          sh -c "npm ci && npm test"
                    '''
                }
            }
        }

        stage('Frontend Build') {
            steps {
                dir('todo-jenkins/frontend') {
                    sh '''
                        podman run --rm \
                          -v "$PWD:/app" \
                          -w /app \
                          node:22-alpine \
                          sh -c "npm ci && npm run build"
                    '''
                }
            }
        }

        stage('Image Build') {
            steps {
                dir('todo-jenkins') {
                    sh '''
                        podman build -t todo-backend:latest ./backend
                        podman build -t todo-frontend:latest ./frontend
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs deleteDirs: true, notFailBuild: true
        }
    }
}